runtime: nodejs10

instance_class: F2

env_variables:
  BUCKET_NAME: "solvestaking.com"

handlers:
- url: /(.*\..*)$
  static_dir: build/\1
  upload: build/(.*\..*)$

- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always
  redirect_http_response_code: 301
  script: auto